Vagrant.configure("2") do |config|
#   config.vm.provider "virtualbox" do |vb|
#       vb.memory = 2048
#       vb.cpus = 2
#   end

  config.vm.define "node-1" do |node1|
      node1.vm.box = "centos/7"
      node1.vm.box_version = "1809.01"
      node1.vm.provider :virtualbox do |vb|
        vb.memory = 2048
        vb.cpus = 1
      end
      node1.vm.network "private_network", ip: "192.168.56.10"
      node1.vm.hostname = "node-1"
      node1.vm.provision "shell", inline: <<-SHELL
      echo "i'm node-1"
      sudo timedatectl set-timezone Asia/Shanghai
      SHELL
      end

  config.vm.define "node-2" do |node2|
      node2.vm.box = "ubuntu/lunar64"
      node2.vm.provider :virtualbox do |vb|
        vb.memory = 2048
        vb.cpus = 1
      end
      node2.vm.network "private_network", ip: "192.168.56.20"
      node2.vm.hostname = "node-2"
      node2.vm.provision "shell", inline: <<-SHELL
          echo "i'm node-2"
          sudo timedatectl set-timezone Asia/Shanghai
      SHELL
  end

end