





  Vagrant.configure("2") do |config|
    ENV["LC_ALL"] = "en_US.UTF-8"

      # 全局配置
      # config.vm.provider "virtualbox" do |v|
      #     v.memory = 2048
      #     v.cpus = 2
      # end
      for i in 1..3 do
        config.vm.define "node-#{i}" do |node|
        node#{i}.vm.box = "ubuntu/focal64"

          node.vm.provision "shell",
            inline: "echo hello from node #{i}"
        end
      end

  end