Vagrant.configure("2") do |config|


  config.vm.define "node-1" do |node1|
      node1.vm.box = "centos/7"
      node1.vm.box_version = "1809.01"
      node1.vm.network "private_network", ip: "192.168.56.10"

      config.vm.network "forwarded_port", guest: 22, host: 8000, auto_correct: true, id: "ssh"


      node1.vm.provider :virtualbox do |v|
        v.memory = 1048
        v.cpus = 1
      end

      node1.vm.hostname = "node-1"
      node1.vm.provision "shell", inline: <<-SHELL
      sudo yum install vim -y
      sudo timedatectl set-timezone Asia/Shanghai
      SHELL
      end

end