ENV["LC_ALL"] = "en_US.UTF-8"

# 1、查看当前的编码设置
# locale
# 2、查看支持的语言
# locale -a
# 3、如果支持 zh_CN.UTF-8 则配置,否则也可以使用en_US.UTF-8进行替代

Vagrant.configure("2") do |config|
    # 全局配置
    # config.vm.provider "virtualbox" do |vb|
    #     vb.memory = 2048
    #     vb.cpus = 2
    #     vb.gui = true # Vagrant允许在VirtualBox中使用GUI界面来显示虚拟机
    # end
    config.vm.boot_timeout = 6000
    # config.ssh.insert_key = false

    config.vm.define "node1" do |node1|
        node1.vm.box = "ubuntu/focal64"

        node1.ssh.insert_key = false
        node1.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
        node1.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      
        # ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        # node1.vm.provision "shell", inline: <<-SHELL
        #     mkdir -p /home/vagrant/.ssh
        #     echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        #     # curl https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub >> output.txt
        #     chown -R vagrant:vagrant /home/vagrant/.ssh
        #     chmod 700 /home/vagrant/.ssh
        #     chmod 600 /home/vagrant/.ssh/authorized_keys
        # SHELL

        node1.vm.provider :virtualbox do |vb|
            vb.memory = "4096"
            vb.cpus = 2
            # vb.name = "node1"
        end
        # node1.vm.synced_folder "./sharedir", "/home/vagrant/sharedir/", create: true, owner: "vagrant", group: "vagrant", mount_options: ["dmode=755","fmode=644"], type: "rsync"
        node1.vm.network "private_network", ip: "192.168.56.10"
        node1.vm.hostname = "node1"
        node1.vm.provision "shell", inline: <<-SHELL
        sudo timedatectl set-timezone Asia/Shanghai
        # 更新apt包索引并安装包以允许apt通过 HTTPS 使用存储库：
        sudo apt-get update
        sudo apt-get install \
           ca-certificates \
           curl \
           gnupg \
           lsb-release
        # 添加 Docker 的官方 GPG 密钥：
        sudo mkdir -m 0755 -p /etc/apt/keyrings
        # 使用以下命令设置存储库：
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        # 安装 Docker 引擎
        sudo chmod a+r /etc/apt/keyrings/docker.gpg #避免默认umask可能配置不正确，导致无法检测存储库公钥文件
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        sudo usermod -aG docker vagrant
        SHELL
        end
end