const sidebars = {
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: 'Back Home', // 这里是链接的标题
      href: '/Default', // 这里是站点的根路径
      className: 'Back-Home-Button', // Class name for styling
    },
  ],
  // coding: [{type: 'autogenerated', dirName: 'Coding'}],  
};

module.exports = sidebars;